version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-api-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    restart: unless-stopped
