services:
  redis:
    image: redis:7-alpine
    container_name: chat-api-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-api-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis_data:
